version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FridayDemo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nv9hbseuwkys"
s3_prefix = "FridayDemo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketNamePrefix=\"sam-demo-mark-11-11-2022\""
